export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_WAITING = 'GET_POSTS_SUCCESS';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_WAITINIG = 'POST_WAITINIG';
