export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_SIGN_REQUEST = 'GET_SIGN_REQUEST';
export const GET_SIGN_SUCCESS = 'GET_SIGN_SUCCESS';
export const GET_SIGN_FAILURE = 'GET_SIGN_FAILURE';
